### ISSUE TITLE
Integrate Slack

### ISSUE THREAD

**Issue by ajira86** [ajira86/docker-taiga#12]
We should add Slack availability in integrations.

> Side note: I've added curl to our taiga base container in order to install the slack extension using benhutchins original script. - @anddann

```
## Install Slack extension
ENV PYTHONIOENCODING UTF-8
RUN LC_ALL=C pip install --no-cache-dir taiga-contrib-slack
RUN mkdir -p /usr/src/taiga-front-dist/dist/plugins/slack/
RUN SLACK_VERSION=$(pip show taiga-contrib-slack | awk '/^Version: /{print $2}') && \
    echo "taiga-contrib-slack version: $SLACK_VERSION" && \
    curl https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$SLACK_VERSION/front/dist/slack.js -o /usr/src/taiga-front-dist/dist/plugins/slack/slack.js && \
    curl https://raw.githubusercontent.com/taigaio/taiga-contrib-slack/$SLACK_VERSION/front/dist/slack.json -o /usr/src/taiga-front-dist/dist/plugins/slack/slack.json
```

**Comment by anddann** [comment]
What do you mean by available modules? I can definitely take a look into this.

**Comment by anddann** [comment]
My idea is to integrate the required code into to `docher-entrypoint.sh` bash script?
What do you think about it?

**Comment by ajira86** [comment]
>My idea is to integrate the required code into to docher-entrypoint.sh bash script?
What do you think about it?

It's ok for me to use the entrypoint. This is an optional integration and we will keep a slimier base image for people who don't want to use it but still let then choose if they want to install or remove it by restarting the container.

**Comment by ajira86** [comment]
I didn't test in complete details this feature at this time but the merge will not affect the project if not used and can be nicely activated or deactivated. I'll certainly test it in a real environment soon.

**Comment by ajira86** [comment]
Made a test in production with a real Slack link, working correctly.
