### ISSUE TITLE
Use enviornment file for env variables

### ISSUE THREAD

**Issue by anddann** [ajira86/docker-taiga#15]
Reminder for my next PR:
Use a seperate environemnt `env` file to separate user editable settings from the core logic, as done here https://github.com/douglasmiranda/docker-taiga
I made a proposal in #17

**Comment by ajira86** [comment]
As I can see, this is a common practice for docker-compose (https://docs.docker.com/compose/env-file/) but file seams to be named `.env` isn't it ?

**Comment by anddann** [comment]
Hi @ajira86,
I'm not a docker export, thus please correct me if I'm wrong.
IMHO: by default .env are used for secrets, e.g., password, magic strings, etc., and are not under version control. However, since I "abuse" it for configuring the container, I named it 'conf.env' to emphasize this purpose. Moreover, it avoids the "ugly" fact, that the file is hidden by default on linux systems :)

**Comment by ajira86** [comment]
> I'm not a docker export, thus please correct me if I'm wrong.

I'm mostly web developer, neither really docker expert.

> IMHO: by default .env are used for secrets, e.g., password, magic strings, etc., and are not under version control.

Not totally sure. With gitlab-ci this kind of secret env vars are directly configured from the project settings in gitlab.

> However, since I "abuse" it for configuring the container, I named it 'conf.env' to emphasize this purpose. Moreover, it avoids the "ugly" fact, that the file is hidden by default on linux systems :)
> IMHO: explicitly naming the file 'conf.env' and explicitly declaring it in the 'Dockerfile' makes the whole building and cofig process less black magic.

I understand your position. I took a short look on some other docker repositories but didn't find project that put env vars in a specific file :/ Should be nice to find a comon way / best practice about this.

**Comment by ajira86** [comment]
Ok, let's use `conf.env`
