### ISSUE TITLE
TypeError in checkdb.py

### ISSUE THREAD

**Issue by Nornort** [ajira86/docker-taiga#20]
I get this issue by launching a simple localhost config of novanet/taiga:

```
Traceback (most recent call last):
  File "/scripts/checkdb.py", line 17, in <module>
    "' password='" + DB_PASS + "'")
TypeError: must be str, not NoneType
Failed to connect to database server or database does not exist.
```

**Comment by ajira86** [comment]
Hello @Nornort, could you please inform us which docker image version you use and how did you launch the container (docker command or docker-compose configuration ?)

This error happens generally when database is not correctly configured.

**Comment by Nornort** [comment]
My bad. Sorry. Fixed using somthing like:

```
docker run -itd \
    --link taiga-postgres:postgres \
    -p 80:80 \
    -e TAIGA_HOSTNAME=localhost \
    -e TAIGA_DB_NAME=taigadb \
    -e TAIGA_DB_HOST=postgres \
    -e TAIGA_DB_USER=postgres \
    -e TAIGA_DB_PASSWORD=password \
    -v ./media:/usr/src/taiga-back/media \
    novanet/taiga
```

And same var in postgres... Perhaps could be changed in Readme...

**Comment by ajira86** [comment]
- [x] clarify readme about minimum db config
- [x] add an explicit error message
- [x] reorganize automated docker build to ensure that latest will not be unstable (and add nightlies for developers)
