### ISSUE TITLE
Nginx configure file linked to wrong available file when using taiga events.

### ISSUE THREAD

**Issue by rushfly** [ajira86/docker-taiga#23]
When active taiga events, /etc/nginx/site-enabled/ include a file: "taiga-events", but the symbol-link is the /etc/nginx/site-available/taiga. So I got an error from browser: Error during WebSocket handshake: Unexpected response code: 200. I think it should be linked to /etc/nginx/site-available/taiga-events.

**Comment by ajira86** [comment]
Thanks for your report, I've to rebuild by test environment to check it
