### ISSUE TITLE
After image creation, you cannot update HOSTNAME

### ISSUE THREAD

**Issue by ajira86** [ajira86/docker-taiga#9]
The configuration for taiga-front cannot be overwritten with a new hostname because of the structure of the sed command. Should be able to replace the hostname at each start.

**Comment by ajira86** [comment]
`sed -ri "s/(\"api\": \"http:\/\/).*(\/api\/v1\/\",)/\1foo\2/g" /taiga/config.json`

**Comment by anddann** [comment]
To avoid a picket fence I would suggest using `#` as a delimiter and including the environment variable `HOSTNAME_TAIGA`
This results in
`sed -ri "s#(\"api\": \"http://).*(/api/v1/\",)#\1$TAIGA_HOSTNAME\2#g" /taiga/config.json`

**Comment by ajira86** [comment]
Oh yes it was just a short example note for me ^^
